CREATE TABLE IF NOT EXISTS trades_tokocrypto (
    id                          BIGSERIAL PRIMARY KEY,
    symbol                      TEXT NOT NULL,
    direction                   TEXT NOT NULL DEFAULT 'long',
    trading_phase               TEXT,
    supervised                  BOOLEAN NOT NULL DEFAULT TRUE,
    entry_order_id              TEXT,
    entry_b_order_id            TEXT,
    entry_status                TEXT,
    entry_price                 NUMERIC(30, 10),
    entry_fill_price            NUMERIC(30, 10),
    entry_fill_time             BIGINT,
    entry_qty                   NUMERIC(30, 10),
    entry_notional_idr          NUMERIC(30, 4),
    slippage_pct                NUMERIC(10, 6),
    slippage_flagged            BOOLEAN NOT NULL DEFAULT FALSE,
    b_order_list_id             TEXT,
    tp_order_id                 TEXT,
    sl_order_id                 TEXT,
    tp_price                    NUMERIC(30, 10),
    sl_price                    NUMERIC(30, 10),
    sl_stop_price               NUMERIC(30, 10),
    sl_limit_price              NUMERIC(30, 10),
    oco_state                   TEXT,
    oco_state_detected_at       TIMESTAMPTZ,
    expired_leg_detected_at     TIMESTAMPTZ,
    exit_status                 TEXT,
    exit_reason                 TEXT,
    exit_price                  NUMERIC(30, 10),
    exit_fill_slippage_pct      NUMERIC(10, 6),
    exit_fill_slippage_flagged  BOOLEAN NOT NULL DEFAULT FALSE,
    exit_time                   BIGINT,
    realized_pnl_idr            NUMERIC(30, 4),
    realized_pnl_pct            NUMERIC(10, 6),
    time_to_resolution_sec      BIGINT,
    planned_rr                  NUMERIC(10, 4),
    risk_pct                    NUMERIC(10, 6),
    slot_size_idr               NUMERIC(30, 4),
    max_slots_at_entry          INT,
    raw_entry_order             JSONB,
    raw_oco_response            JSONB,
    raw_exit_detail             JSONB,
    open_time                   TIMESTAMPTZ DEFAULT NOW(),
    created_at                  TIMESTAMPTZ DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ DEFAULT NOW(),
    correlation_cluster_id      TEXT
);
CREATE INDEX IF NOT EXISTS idx_toko_exit_status  ON trades_tokocrypto (exit_status);
CREATE INDEX IF NOT EXISTS idx_toko_symbol       ON trades_tokocrypto (symbol);
CREATE INDEX IF NOT EXISTS idx_toko_open_time    ON trades_tokocrypto (open_time DESC);
CREATE INDEX IF NOT EXISTS idx_toko_entry_order  ON trades_tokocrypto (entry_order_id);
CREATE INDEX IF NOT EXISTS idx_toko_b_list_id    ON trades_tokocrypto (b_order_list_id);
